### ISSUE TITLE
How to use this script for reading in CVRs in the wild

### ISSUE THREAD

**Issue by kuriwaki** [HiltonRoscoe/CDFPrototype#11]
I'm a researcher using CVRs to study vote choice patterns. I'm looking for ways to translate CVR files into datasets that can be analyzed in e.g. R. 

For example, San Francisco uploads their CVR as JSON files: https://sfelections.sfgov.org/november-3-2020-election-results-detailed-reports (See under Final Report, "Cast Vote Record (Raw data) - JSON").  Attached is an example JSON file. 

How should I go about using the resources on this repo to read this in extract the entries I care about (e.g., precinct information and vectors of vote choice at each voter/ballot level).

[CvrExport_24882.json.zip](https://github.com/HiltonRoscoe/CDFPrototype/files/5755706/CvrExport_24882.json.zip)

**Comment by JDziurlaj** [comment]
Hi @kuriwaki. Thanks for reaching out. Unfortunately, the files you reference are not in the NIST CVR CDF format. They are likely in a vendor specific format, which these tools will not help you out with. Perhaps @cjerdonek would be able to help you with this.

**Comment by cjerdonek** [comment]
Hi @kuriwaki, @JDziurlaj is right. Those files are vendor-specific. I'm a software developer and serve on the San Francisco Elections Commission and have looked at those files at certain points. Here are the files for the most recent election, as I'm sure you know:
https://sfelections.sfgov.org/november-3-2020-election-results-detailed-reports

My recommendations are:

* Click on the question mark symbol next to "Cast Vote Record (Raw data) - JSON." It should provide a PDF with some vendor provided documentation of the export files (the vendor is Dominion).
* The JSON file format shouldn't be too hard to examine by hand to figure out what the various key-values mean. And because it's JSON, it doesn't require any parsing, which is otherwise the most annoying part.
* Click the "Use our contact form to request or suggest a data set" at the top of the results page if you have San Francisco specific questions about the data listed there. For example, you might be after further information about the precincts in San Francisco, like shape files.

**Comment by kuriwaki** [comment]
Thank you for the swift reply and Chris for your really pertinent expertise. I didn't notice the documentation under the question mark symbol; this will make things much easier.
